version: '3'
services:

  mysql:
    image: 'mysql:5.7.16'
    restart: always

    # private container network ports
    expose:
      - '3306'

    environment:
      MYSQL_ROOT_PASSWORD: 'changeme'
    volumes:
      - ./database:/var/lib/mysql

  server:
    depends_on:
      - mysql
    image: 'cmangos:wotlk'

    # public ports
    ports:
      - '8085:8085'
      - '3724:3724'

    # private container network ports
    expose:
      - '3443' # mangosd remote access

    restart: always
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'root'
      MYSQL_PWD: 'changeme'
      MYSQL_MANGOS_USER: 'mangos'
      MYSQL_MANGOS_PWD: 'mangos'
      MANGOS_GAMETYPE: 1
      MANGOS_MOTD: 'Welcome!'
      MANGOS_REALM_NAME: 'cmangos'
      MANGOS_SERVER_PUBLIC_IP: '127.0.0.1'
      MANGOS_DISABLE_PLAYERBOTS: 0
      MANGOS_AUCTIONBOT_SELL_CHANCE: 40
      MANGOS_AUCTIONBOT_BUY_CHANCE: 10
      CONTAINER_TIMEZONE: 'Etc/UTC'
      MANGOS_REV: '4161a090bfa7acae111d497de4aadbe182874292' # revision of https://github.com/cmangos/mangos-wotlk , or 'master' if you want latest
      DB_REV: '62b1248d48453ae1cf6de3e945ac1d521f163798' # revision of https://github.com/cmangos/wotlk-db , or 'master' if you want latest
    volumes:
      - ./resources/maps:/opt/mangos/maps
      - ./resources/vmaps:/opt/mangos/vmaps
      - ./resources/mmaps:/opt/mangos/mmaps
      - ./resources/dbc:/opt/mangos/dbc

  backup:
    depends_on:
      - mysql
    image: databack/mysql-backup
    restart: always
    volumes:
     - ./backups:/db
     #- /path/to/pre-backup/scripts:/scripts.d/pre-backup
     #- /path/to/post-backup/scripts:/scripts.d/post-backup
    environment:
      DB_DUMP_TARGET: '/db'
      DB_USER: 'root'
      DB_PASS: 'changeme'
      DB_DUMP_FREQ: '1440' # minutes between backups. 1440 = once per day. Note that min backup size is ~50MB or so.
      DB_DUMP_BEGIN: '+5' # how long to wait before backup
      DB_SERVER: 'mysql' # docker service name of server to backup